### ISSUE TITLE
Difficulties with setting up the maze environments

### ISSUE THREAD

**Issue by pavlosSkev** [kngwyu/mujoco-maze#5]
Hello. I am having some trouble with making it work. What is the process for making a U-Maze Ant environment?

Also, when I import "from mujoco_maze.ant import AntEnv" and try to initialize, the __init__ of AntEnv misses a path string.
What should that path be?

Thanks in advance.

**Comment by kngwyu** [comment]
Thanks for your interest.
 Environments are accessible via `gym.make`.
I added [an example](https://github.com/kngwyu/mujoco-maze#usage) on README.

**Comment by pavlosSkev** [comment]
> Thanks for your interest.
> Environments are accessible via `gym.make`.
> I added [an example](https://github.com/kngwyu/mujoco-maze#usage) on README.

**Comment by pavlosSkev** [comment]
Thank you. Didn't even cross my mind it's this simple. Great work.
